### ISSUE TITLE
UI for data change

### ISSUE THREAD

**Issue by richteralexander** [richteralexander/plex#12]
Currently, the user has to open the yml files to change project, software etc. settings.
Which can be tricky and you should have a basic understanding of yml syntax.

A simple UI could the editing process easier and more robust since the input could be guided and checked beforehand. Variables like _!env_first_ could be added as template.

Simple Example:
![ui](https://user-images.githubusercontent.com/9514022/28029231-a6023e9e-659f-11e7-9eee-9939a6e1a896.PNG)

**Comment by mottosso** [comment]
I would recommend going the other way - make editing yml files easier. It'll save you from maintaining a GUI, and enable those who edit it to do so under their own terms. For example, some enjoy Vim, others Sublime. Configuration files are part of daily life to many, and they'll likely have their own workflow for it.

One of the things you could do is have the user run a YAML linter, it could keep track of errors interactively. Another thing you could do is put an intermediate step between reading an end-user's YAML file and actually using it in your software.

```bash
$ echo "my_custom: edit" >> config.yml
$ python -m plex --update-configuration ./config.yml
```

That'll enable you to do validation on it and parse your DSL, and prevent the user from accidentally breaking the file.

**Comment by richteralexander** [comment]
The idea for the UI is that also artist/producer (non-programmer) could modify it since that is what they should do. If the UI builds itself procedurally there is no maintaining.

YAML Linter could be a fast solution.
The intermediate is the UI solution which not just checks the input and wouldn't allow the saving of broken configs but also solves the problem of not having great programming skills.

**Comment by mottosso** [comment]
Cool.

I'd question whether editing the file in a text editor is any more error prone or difficult than editing it in that GUI. What are the benefits?

I'd also not underestimate your fellow non-programmers. Editing text doesn't necessarily  need to be an ordeal.

**Comment by richteralexander** [comment]
Before saving the config there is a check, so you can just save if the syntax is correct.
The UI would on one hand combine all the config files into one overview, you dont have to navigate and find the config folder, it is more appealing for non programmers and you can fill it with tooltips and help out with expressions like (!env_first).

It is less of underestimating but more of appealing and expectations. Non-programmer are mostly not used to change config files and will be hesitant or wrong guided in using them.
The scripts are for programmer but the configs are for artists and producer.
