### ISSUE TITLE
Port to Linux & Mac

### ISSUE THREAD

**Issue by richteralexander** [richteralexander/plex#13]
Plex is currently just running on Windows. 
With some modifications in the code based on OS specifics, this could be fixed and would allow the use in different OS systems.

**Comment by mottosso** [comment]
Consider making every interaction with Plex happen through a Python command-line interface. That way you can avoid platform specific shell scripts, like `.bat` or `.sh`.

**plex**

```python
#!/usr/bin/env python
import argparse
parser = argparse.ArgumentParser("say")
args = parser.parse_args()
print(args.say)
```

Then you can call it like this.

```bash
$ plex "Hello"
# Hello
```

On Windows, Python scripts are run via Python Launcher, and on other platforms they run natively via the shell.

**Comment by richteralexander** [comment]
You can already do that in data/pipeline.py. That is the only thing the batch is doing on Windows.

```batch
python %~dp0\..\data\pipeline.py %1 --script software --software maya
```
With port, I mostly meant some problems with commands and paths which can behave differently on other OS or are not recognized.
