### ISSUE TITLE
Hi i having this error "ImportError: No module named subclass"

### ISSUE THREAD

**Issue by tws0002** [richteralexander/plex#14]
Hi, 

```
C:\Users\Des-PC>K:\SES\Library\plex\exe\win_desktop.bat
Traceback (most recent call last):
  File "K:\SES\Library\plex\exe\\..\data\pipeline.py", line 195, in <module>
    import arDesktop
  File "K:\SES\Library\plex\lib\utils\arDesktop.py", line 25, in <module>
    from tank import Tank
  File "K:\SES\Library\plex\lib\classes\tank.py", line 6, in <module>
    from users import User
  File "K:\SES\Library\plex\lib\classes\users.py", line 22, in <module>
    from subclass import Singleton
ImportError: No module named subclass
```
Please Help 

Thanks 
Desmond

**Comment by richteralexander** [comment]
Thanks for the feedback!
I added the missing class. Try again with the new version.

**Comment by richteralexander** [comment]
There is a new update with more robust features. 
Especially arDesktop has now the admin options as default (so you see more options)

**Comment by tws0002** [comment]
Hey, Thanks for the quick fix!! is working now!! 
for arDesktop admin options is still under development right?
it would be great if we can have a project management tools to manage studio project!!

I found another error on Plex Maya shelf tools!! will open another new issue for that!!

**Comment by richteralexander** [comment]
Great to hear!
What do you mean with: "admin options is still under development"? 
Do you miss something/something breaks?

Do you mean save and load with "project management tool"?

**Comment by tws0002** [comment]
not sure am I doing it correctly!! 
when I click on the admin/Project Data it just leads me to the plex\data\project\default directory!! 
is that what you are doing?

or there is an interface will pop out when I clicked?

**Comment by richteralexander** [comment]
:D yeah it is just a quick add to show that "admin" settings etc are possible and a quick way to get to the log and config files.
