### ISSUE TITLE
Save current shot/asset as a new one

### ISSUE THREAD

**Issue by wickedmonkey** [richteralexander/plex#18]

**Comment by richteralexander** [comment]
possibility to switch from arSave to arSaveAs -> add button for switch

**Comment by richteralexander** [comment]
Added saveAs button to Save to switch to SaveAs and save a new from this file

![save](https://user-images.githubusercontent.com/9514022/31848845-c70a1db0-b639-11e7-95a8-376eb86abe04.PNG)
